[project]
name = "postgresql-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0.0",
    "psycopg[binary]>=3.2.6",
    "psycopg-pool>=3.2.6",
    "anthropic>=0.40.0",
    "mcp>=1.0.0",
]
